# Generated by Django 5.0.7 on 2025-03-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bmi',
            field=models.FloatField(editable=False),
        ),
    ]
