# Generated by Django 5.0.7 on 2025-04-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_visible_in_leaderboard',
            field=models.BooleanField(default=True),
        ),
    ]
