# Generated by Django 5.0.7 on 2025-04-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='is_visible_in_leaderboard',
        ),
    ]
