# Generated by Django 5.0.7 on 2025-04-19 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0002_remove_activitylog_is_visible_in_leaderboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='distance',
        ),
    ]
