# Generated by Django 5.0.7 on 2025-04-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0003_remove_activitylog_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='weight_kg',
            field=models.FloatField(default=0.0),
        ),
    ]
